/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "daVarRpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include <time.h>
#define _xdr_result xdr_result
#define _xdr_argument xdr_argument

void
davarsvr_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *davar_ackmessage_1_arg;
		char *davar_getlist_1_arg;
		NAMELIST davar_readmultiple_1_arg;
		WVALLIST davar_writemultiple_1_arg;
		TESTNAMELIST davar_readmultiple_test_1_arg;
		RVALLIST davar_readmultiple_test_cb_1_arg;
		char *davar_readpatternmatch_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case DAVAR_ACKMESSAGE:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) davar_ackmessage_1_svc;
		break;

	case DAVAR_GETLIST:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_NAMELIST;
		local = (char *(*)(char *, struct svc_req *)) davar_getlist_1_svc;
		break;

	case DAVAR_READMULTIPLE:
		_xdr_argument = (xdrproc_t) xdr_NAMELIST;
		_xdr_result = (xdrproc_t) xdr_RVALLIST;
		local = (char *(*)(char *, struct svc_req *)) davar_readmultiple_1_svc;
		break;

	case DAVAR_WRITEMULTIPLE:
		_xdr_argument = (xdrproc_t) xdr_WVALLIST;
		_xdr_result = (xdrproc_t) xdr_ERRLIST;
		local = (char *(*)(char *, struct svc_req *)) davar_writemultiple_1_svc;
		break;

	case DAVAR_READMULTIPLE_TEST:
		_xdr_argument = (xdrproc_t) xdr_TESTNAMELIST;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) davar_readmultiple_test_1_svc;
		break;

	case DAVAR_READMULTIPLE_TEST_CB:
		_xdr_argument = (xdrproc_t) xdr_RVALLIST;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) davar_readmultiple_test_cb_1_svc;
		break;

	case DAVAR_READPATTERNMATCH:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_WVALLIST;
		local = (char *(*)(char *, struct svc_req *)) davar_readpatternmatch_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
